.gitignore
ios/Flutter/AppFrameworkInfo.plist
ios/Podfile
ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
pubspec.lock

should increase ios build times and changes ios support to >= 12.0

Fix build issues

---

android/app/google-services.json
ios/Podfile.lock
ios/Runner/Info.plist
lib/pages/homePage.dart
lib/pages/signInPage.dart
lib/services/auth.dart
pubspec.lock
pubspec.yaml

Added changes so users can sign in with google accounts using google sign in dart api (https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in/lib/google_sign_in.dart).

Google auth

---

lib/pages/homePage.dart

adds a method to calculate restaurant distances from user

restaurant distances

---

lib/models/menuItem.dart
lib/services/documenu.dart
test/documenu_test.dart

adds support for "GET Menu Items For Restaurant" document endpoint

menu items from restaurant id

---

firebase/functions/index.js
lib/pages/backendTestPage.dart
lib/pages/homePage.dart
lib/pages/profilePage.dart
lib/services/auth.dart
lib/services/fsmanager.dart
lib/services/ratings.dart

Added fsmanager functions for writing and updating ratings, finding ratings from a userid and menuitemid, and getting a specific field from a document, given the docs id, and what field you want to retrieve. (Useful for getting a menu items average rating, or getting the rating a user left for a specific item, etc)

Firestore updates

---

firebase/firebase.json
firebase/functions/index.js
firebase/functions/package-lock.json
firebase/functions/package.json
firebase/functions/test/index.test.js

Adds multiple cloud functions such as:
- on rating create add it to userInfo ratedItems
- on rating create/update/delete update menu item doc
- on user create/delete their userInfo doc
- on userInfo delete delete their rating docs
Also includes boilerplate for cloud functions test suite with 1 test case to be ran on local firebase emulator
Will deploy when merged

Cloud functions update

---

lib/components/menuItemListTile.dart
lib/components/ratingModal.dart
lib/pages/homePage.dart
lib/pages/restaurantPage.dart
pubspec.lock
pubspec.yaml

Rating modal functionality done and hooked up to backend
Ready for David tomorrow

Rating modal

---

lib/models/restaurant.dart
lib/pages/restaurantPage.dart
lib/services/documenu.dart
lib/services/menuUtil.dart
pubspec.lock
test/documenu_test.dart

Adds menuUtil.dart which provides functionality for building a sectioned menu for a given restaurant
Changes restaurant page to use this new Menu paradigm
Adds one test to show how to build a menu for a restaurant

Item categories

---

firebase/functions/index.js
lib/components/menuItemListTile.dart
lib/components/ratingModal.dart
lib/pages/backendTestPage.dart
lib/pages/restaurantPage.dart
lib/services/fsmanager.dart

This change keeps track of the restaurant id for a menu item in the rating documents for that menu item, and the menuitem document for that menu item. 
This change will be needed for creating a restaurant page to keep a sorted list of all the rated items.

RestaurantId

---

firebase/functions/index.js

Fixed an issue when setting the restaurant doc that was causing cloud functions **menuItemRated** and **menuItemUpdated** to timeout after they were deployed.
( Removed the await db.runTransaction(async (transaction) => {) that was surrounding the transaction.set() )
---
Functions are already deployed, but will still re-deploy after this PR is merged
---
PS I realized too late that i named this branch gfcFix instead of gcfFix. oopsie :(

fixed timeout issue

---

lib/components/menuItemListTile.dart
lib/components/ratingModal.dart
lib/pages/homePage.dart
pubspec.lock

Reverting back to rating modal, matching new modal wireframes (to the best of my abilities), and fixing pin resizing issue on the homepage.

Rating page

---

lib/components/menuItemListTile.dart
lib/models/menuItemFirestore.dart
lib/services/fsmanager.dart
pubspec.lock
pubspec.yaml

Change to add live updates for menu item average ratings on the restaurant page.
This is done by wrapping the Text that displays the avgRating with a StreamBuilder, and streaming the DocumentSnapshot for the menuItem. We then display the text based off of the snapshots avgRating, and whenever the document refreshes, the StreamBuilder also refreshes that portion of the menuItemListTile.

Live rating update

---

lib/components/mostPopularItemCard.dart
lib/pages/homePage.dart
lib/pages/registerPage.dart
lib/pages/signInPage.dart
pubspec.lock
pubspec.yaml

Matches WireFrames and Nav updated

Sign in page

---

lib/pages/homePage.dart
lib/services/auth.dart
lib/services/fsmanager.dart
lib/util/itemListUtil.dart

Get list of menu items that the user has previously rated.
Also makes AuthService and FirestoreManager singletons
@bkingsley727 Use like 
```
List<Future<MenuItem>> menuItems = await ItemListUtil.getPreviouslyRatedItems();
for (Future<MenuItem> futureItem in menuItems) {
MenuItem item = await futureItem;
}
```

Prev rated items backend

---

ios/Podfile.lock
lib/pages/homePage.dart
lib/services/documenu.dart
pubspec.lock
pubspec.yaml

Cache's api calls to data provider on the client device.
Search is a bit faster now because it only actually does a search api call when no key has been pressed for 500ms.

External api optimization

---

lib/pages/homePage.dart
lib/services/documenu.dart
lib/util/searchUtil.dart
test/documenu_test.dart

Search for items by name or description keyword
`var items = await SearchUtil.menuItemByGeoAndName(currentLocation, mileRadius, "pizza");`
also changes `restaurantSearchUtil.dart` to just `searchUtil.dart`

item search works

---

lib/components/prevRatedItemTile.dart
lib/components/ratingModal.dart
lib/main.dart
lib/pages/prevRatedItemsPage.dart
lib/pages/profilePage.dart

Implemented previously rated items page just needs to be connected to profile page.

Prev rated items page

---

ios/Podfile.lock
lib/pages/profilePage.dart
lib/services/auth.dart
pubspec.lock

• App bar has title and correct color now
• When changing password, page displays messages

Profile page app bar and error handling

---

lib/components/menuItemListTile.dart
lib/components/menuItemSearchTile.dart
lib/components/mostPopularItemCard.dart
lib/components/prevRatedItemTile.dart
lib/pages/homePage.dart
lib/pages/prevRatedItemsPage.dart
lib/pages/restaurantPage.dart
lib/util/geoUtil.dart
lib/util/itemListUtil.dart
pubspec.lock
pubspec.yaml

Item Search
Scroll to Menu Item in restaurant
Fixed missing info on Restaurant Header
Added Open in Maps

Item search

---

lib/pages/homePage.dart

Rework when to reset the list

---

lib/components/prevRatedItemTile.dart
lib/pages/prevRatedItemsPage.dart

Quick fix for rating history page.

Fix RatingHistory issue.

---

lib/models/menuItem.dart
lib/pages/homePage.dart
lib/pages/prevRatedItemsPage.dart

MenuItem Builder returns null in the case where the given itemID was not found by the data API.
Protects cases where user tries to GET an item that is in Documenu but not Mocumenu such as
- mocumenu call for a previously rated an item that is only in Documenu
- mocumenu call a popular item nearby that is only in Documenu

Safeguard Item Builder

---

lib/components/menuItemSearchTile.dart
lib/pages/homePage.dart

Sorts the results of menu item search by distance to user. Items at the same location get sorted by avg rating, highest to lowest.
---
This is done by creating a helper class in menuItemSearchTile (called SearchTileAndData) that stores the tile and the data needed for sorting (That data being distance and average rating). Since the data is passed to the MenuItemSearchTile as Futures, we need some way to convert them to actual values before we return the list of MenuItemSearchTiles. This happens in the setVariables() method of the helper class, which we call for every menu item before we sort. It ensures the data has been returned and converted before sorting occurs, that way compareTo() can be called on the values.
So, once we retrieve the list of MenuItems in homePage.dart, we then …

Sort menu item search results

---

misc/populate.py
misc/verify.py

A bunch of python that I wrote to deal with verifying D ocumenu's wack data

Mocumenu add locations

---

lib/main.dart

Make banner go away in debug mode

banner off

---

lib/components/prevRatedItemTile.dart
lib/pages/prevRatedItemsPage.dart

Had to remove future restaurants because of weird UI bug

Prev rated sorts

---

lib/components/ratingModal.dart

Changed routing of the rating modal so that after a user signs in the rating modal is not still there directing user to sign in.

Changed routing of rating modal.
